trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: MyVariableGroup

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
      displayName: 'Use Python 3.8'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - script: |
        python -m pytest tests/
      displayName: 'Run tests'

- stage: Deploy
  jobs:
  - deployment: DeployToStaging
    environment: staging
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              # Deploy to staging server
              ssh $(staging_user)@$(staging_host) './deploy.sh'
            displayName: 'Deploy to Staging'
            env:
              staging_host: $(staging_host)
              staging_user: $(staging_user)
              staging_password: $(staging_password)
