# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1signup():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1signup(self):
    self.driver.get("http://localhost:5000/")
    self.driver.set_window_size(786, 656)
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "Contact Us").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mb-4:nth-child(1) > .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mb-4:nth-child(1) > .form-control").send_keys("01033998")
    self.driver.find_element(By.CSS_SELECTOR, ".mb-4:nth-child(2) > .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mb-4:nth-child(2) > .form-control").send_keys("hajar.alshafai@")
    self.driver.find_element(By.CSS_SELECTOR, ".mb-4:nth-child(2) > .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mb-4:nth-child(2) > .form-control").send_keys("hajar.alshafai@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".mb-4:nth-child(3) > .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mb-4:nth-child(3) > .form-control").send_keys("zayed")
    self.driver.find_element(By.CSS_SELECTOR, ".mb-3 > .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mb-3 > .form-control").send_keys("i am having troubles using website")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Signup").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("HajarFawzi12@gmail.com")
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("HajarFawzi12")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("HajarFawzi@123")
    self.driver.find_element(By.NAME, "confirm_password").click()
    self.driver.find_element(By.NAME, "confirm_password").send_keys("HajarFawzi@123")
    self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".title-2").click()
  
